In [1]:
import torch
from torch import nn, Tensor
from torch.nn import Parameter, MSELoss

In [5]:
linear = nn.Linear(in_features=3, out_features=2, bias=True)
print(linear.weight.shape)


linear.weight = Parameter(torch.tensor([[-1., 2., -3.],
                                        [4., 5., -6.]]))

linear.bias = Parameter(torch.tensor([-1., 3.]))

model = nn.Sequential(linear)

x = Parameter(Tensor([0., 1., 2.]))
y = model(x)
print(y)
print(x.shape)
print(y.shape)

manual_loss = Tensor([-4, -3])
y.backward(manual_loss)
print(x.grad)
print(linear.weight.grad)
print(linear.bias.grad)



torch.Size([2, 3])
tensor([-5., -4.], grad_fn=<ViewBackward0>)
torch.Size([3])
torch.Size([2])
tensor([ -8., -23.,  30.])
tensor([[-0., -4., -8.],
        [-0., -3., -6.]])
tensor([-4., -3.])
