In [6]:
from torch import nn, Tensor
from torch.nn import Parameter, Softmax, ReLU

In [23]:
f = nn.Softmax(dim=0)
x = nn.Parameter(Tensor([-1., 0., 1., 2., 5., -6.]), requires_grad=True)
y = f(x)
print(y)

test = nn.Parameter(Tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]))
print(test.shape)
with torch.no_grad():
    target = y+ Tensor([-1., 0., 1., 1, -5, -1.])

loss_fn = nn.MSELoss()
loss = loss_fn(y, target)
loss.backward()

print(x.grad)

tensor([2.3008e-03, 6.2543e-03, 1.7001e-02, 4.6213e-02, 9.2822e-01, 1.5503e-05],
       grad_fn=<SoftmaxBackward0>)
torch.Size([2, 2, 3])
tensor([-2.7458e-03, -9.5486e-03, -3.1623e-02, -8.5959e-02,  1.2989e-01,
        -1.8501e-05])


In [56]:
criterion = nn.CrossEntropyLoss()
logits = torch.tensor([[2.0, 1.0, 0.1]])

target1 = torch.tensor([0])
fake_param1 = Parameter(torch.zeros_like(logits), requires_grad=True)
loss1 = criterion(logits+fake_param1, target1)
print(loss1.item())
loss1.backward()
print(fake_param1.grad)

print("")

target2 = torch.tensor([[0.9, 0.1, 0.]])
fake_param2 = Parameter(torch.zeros_like(logits), requires_grad=True)
loss2 = criterion(logits+fake_param2, target2)
print(loss2.item())
loss2.backward()
print(fake_param2.grad)



0.4170299470424652
tensor([[-0.3410,  0.2424,  0.0986]])

0.5170299410820007
tensor([[-0.2410,  0.1424,  0.0986]])


In [21]:
conv1d = nn.Conv1d(in_channels=2, out_channels=3, kernel_size=3, padding=0)

model = Sequential(conv1d)
model[0].weight = Parameter(
    Tensor([[[-1., 0., 1.], [-1., 2., 3.]], 
            [[0., 0., 0.], [1., -1., -2.]], 
            [[-2., -1., -2.], [-3., -1., 0.]]]))
model[0].bias = Parameter(Tensor([0.,1.,2.]))

x = Tensor([[ [1.,2.,3.,4.,5.,6.], [-1.,-2.,-3.,-4.,-5.,-6.] ]])
x.requires_grad = True
y = model(x)
print(y)
loss_fn = MSELoss()
with torch.no_grad():
    target = y+Tensor([[ [-1.,0.,-2.,-1.], [1.,0.,-2.,-4.], [-2.,-1.,0.,-1.] ]])
print(target)
loss = loss_fn(y, target)
loss.backward()


print("FIRST CONVOLUTION")
print("Gradient wrt x:")
print(x.grad)
print("Gradient wrt weights:")
print(model[0].weight.grad)
print("Gradient wrt bias:")
print(model[0].bias.grad)
print("")
print("--------------------------")

print("SECOND CONVOLUTION")
print("Gradient wrt x:")
print(x.grad)
print("Gradient wrt weights:")
print(model[0].weight.grad)
print("Gradient wrt bias:")
print(model[0].bias.grad)


tensor([[[-10., -14., -18., -22.],
         [  8.,  10.,  12.,  14.],
         [ -3.,  -4.,  -5.,  -6.]]], grad_fn=<ConvolutionBackward0>)
tensor([[[-11., -14., -20., -23.],
         [  9.,  10.,  10.,  10.],
         [ -5.,  -5.,  -5.,  -7.]]])
FIRST CONVOLUTION
Gradient wrt x:
tensor([[[-0.8333, -0.6667, -1.0000, -0.8333,  0.1667, -0.1667],
         [-1.3333, -0.3333,  0.6667,  0.3333, -0.1667, -0.8333]]])
Gradient wrt weights:
tensor([[[ 1.8333,  2.5000,  3.1667],
         [-1.8333, -2.5000, -3.1667]],

        [[ 3.5000,  4.3333,  5.1667],
         [-3.5000, -4.3333, -5.1667]],

        [[ 1.3333,  2.0000,  2.6667],
         [-1.3333, -2.0000, -2.6667]]])
Gradient wrt bias:
tensor([0.6667, 0.8333, 0.6667])

--------------------------
SECOND CONVOLUTION
Gradient wrt x:
tensor([[[-0.8333, -0.6667, -1.0000, -0.8333,  0.1667, -0.1667],
         [-1.3333, -0.3333,  0.6667,  0.3333, -0.1667, -0.8333]]])
Gradient wrt weights:
tensor([[[ 1.8333,  2.5000,  3.1667],
         [-1.8333, -2.500